ss/examples/upload/main.go
Addresses Issue #40 
FileUpload `Name` is "source". Otherwise, a 500 error happens on upload.
=> SS FileUpload object Name is 'source' not file name

CHANGELOG.md, httpclient/http.go, httpclient/http_test.go
http.ProxyFromEnvironment is what is normally used for the DefaultTransport, so this is just resetting this to the correct default.
Avoids issue where if http_proxy is set, authentication part was not going through proxy though subsequent requests were.
=> IV-1637 Fix authentication to work through proxy

rsapi/auth.go
Not all endpoints use the 'us-3.rightscale.com' style host. This commit
removes the assumption that there will be a 'us' substring in the login
host. Fixes #45.
=> Fix SS host string substitution for SS host names

ss/examples/basic/main.go, ss/examples/upload/main.go
This is the correct link to access to this reference page. The old one is soon going to be invalid due to bucket migration.
=> Tl 434 fix references to old rs api docs

cm15/attributes.json, cm15/codegen_client.go
Resource InstanceType currently has attribute local_disk_size set to string, but the actual json document is returning an int (not sure if this is cloud dependant or not). ex:
```json
{  
"resource_uid":"1",
"name":"small",
"description":"canned type small",
"memory":"1GB",
"cpu_speed":"",
"cpu_count":1,
"cpu_architecture":null,
"local_disks":0,
"local_disk_size":0,
"links":[  ],
"actions":[  ]
},
{  
"resource_uid":"3",
"name":"small (memory reserved)",
"description":"canned type small",
"memory":"1GB (Memory Reservation)",
"cpu_speed":"1Ghz",
"cpu_count":1,
"cpu_architecture":null,
"local_disks":1,
"local_disk_size":10,
"links":[  ],
"actions":[  ]
}
```
with the attribute defined as string was getting "cannot unmarshal number into Go value of type string".
=> Change type of local_disk_size attribute for InstanceType resource

ca/cac/codegen_metadata.go, cm15/codegen_metadata.go, gen/writers/metadata.go, ss/ssc/codegen_metadata.go, ss/ssd/codegen_metadata.go, ss/ssm/codegen_metadata.go
This is a follow up PR to https://github.com/rightscale/rsc/pull/53 and differentiates between QueryParam and PayloadParam in the name in APIParams metadata.
=> SS-2670 Fix array query params in metadata.

Godeps/Godeps.json, httpclient/http.go, rsapi/http.go
This PR adds support for using golang.org/x/net/context with HTTP requests. It can be used to cancel requests after certain period.
=> SS-3010 Support context-aware http requests.

rsapi/auth.go, rsapi/rsapi.go
The token authenticator doesn't send the X-Account header. This is
required for the CM16 API. So added a NewTokenAuthenticatorWithAccountID
function which will set the account ID and use it in the X-Account
header upon signing the request if provided.
=> SS-3009 Use account ID with token authenticator.

cm15/attributes.json, cm15/codegen_client.go
While working with publications noticed the type was wrong. Example:
~~~
rsc cm15 index /api/publications 'filter[]=name==RL10 Linux Setup Hostname' | python -m json.tool
[
{
"actions": [
{
"rel": "import"
}
],
"commit_message": {
"text": "Sync with github repo",
"time": "2015/09/24 23:40:45 +0000",
"user": "efrain@rightscale.com"
},
"content_type": "RightScript",
"created_at": "2015/09/25 03:01:37 +0000",
"description": "Changes the hostname of the server.",
"links": [
{
"href": "/api/publications/209498",
"rel": "self"
},
{
"href": "/api/publication_lineages/55956",
"rel": "lineage"
}
],
"name": "RL10 Linux Setup Hostname",
"publisher": "RightScale",
"revision": 2,
"revision_notes": null,
"updated_at": "2015/10/02 23:55:23 +0000"
}
]
~~~
=> Attribute type for Publication.CommitMessage was incorrect

Makefile
Sheldon ran into a bunch of .go-e files showing up when he was trying to release a new version of rsc, this should fix his problem.
=> Make govers and unvers targets work on Mac OS X and other platforms

.gitignore, README.md, glide.lock, glide.yaml, httpclient/http.go, log/doc.go, log/log.go, rsapi/rsapi.go
Modifies the HTTP client so that if a request explicitly states a scheme (HTTP or HTTPS) then we will use the scheme instead of the 'Insecure' flag.
=> Ss 3011 respect scheme in request

httpclient/http.go
@ryanwilliamson prefer the X-Request-Id header as request token for logging
=> SS-4154_respect_request_id_header

ca/ca.go, ca/commands.go, ss/commands.go, ss/ss.go
@sheldon-b fix concurrent map write crash
looks like we reinitialized the same global for ss and ca package every time a new client was created
should only have to initialize once for each package
=> SS-4680_fix_concurrent_map_write_crash

httpclient/http.go, httpclient/http_test.go
@arangamani added httpclient.NewPB() to create client without using any package variables
handles case where package variables change on web handler go-routines (specifically, httpclient.NoCertCheck)
=> SS-4753_no_globals_client

glide.lock, glide.yaml, httpclient/http.go, rsapi/http.go
@ajoulie changed to use built-in context package from go 1.7+
the golang.org/x/net/context/ctxhttp package is not built-in and cannot work with the built-in context
copied ctxhttp.Do() to ctxhttpDo() in order to resolve this
=> SS-4837_use_builtin_context

command_line.go, config.go, config_test.go
Absolute minimum code to support usage of a refresh token within the config file if it exists. User can now set the refresh token using `rsc setup`. The main advantage is that no extra cli options are needed for users that use OAuth2 when consuming `~/.rsc` or via `--config`.
Addresses issue #77.
=> Support OAuth/refresh token from config

config.go
This was accidentally left out of PR #102, adding now to secure the refresh token on the client machine.
=> Mask the refresh token in setup process

CHANGELOG.md, metadata/action.go, recording_test.go, rsapi/commands.go
- The code for matching an href with the right resource and action
assumed that the MatchHref method actually checked for exact matches;
however, this was not actually the case even though it seems to be the
intention so I fixed MatchHref to actually return true only when there
is an exact match.
- I also cleaned up the exact match code to use Golang's labelled break
feature.
=> Fix resource href parsing to correctly exact match

.gitignore, Makefile, RELEASING.md
- Add step to remove `vendor` directory before running `make govers` in
RELEASING.md to work around it looking there, messing up, and missing
the top level directory. This is the message that `govers` would print
but not actually return an error on:
```
govers: cannot import "github.com/rightscale/rsc/vendor/github.com/onsi/ginkgo/integration/_fixtures/convert_goldmasters" from "/home/douglas/go/src/github.com/rightscale/rsc": found packages tmp (extra_functions_test.go) and subpackage (nested_subpackage_test.go) in /home/douglas/go/src/github.com/rightscale/rsc/vendor/github.com/onsi/ginkgo/integration/_fixtures/convert_goldmasters
```
- Update to latest Glide.
- Add evil `.DS_Store` to `.gitignore`. How did this not happen already?
=> Better RELEASING.md to deal with govers vendor bug

httpclient/http.go
Allow the User-Agent header to be passed from plugins to aws cloudtrails.
=> allow setting of user-agent in http(s) request

.travis.yml, CHANGELOG.md, cm15/ruby_time.go
- With the previous implementation, `RubyTime` objects would not necessarily have the location set to `time.UTC` depending on the time zone settings where they are run. This is definitely a problem when trying to write unit tests for things using `cm15` objects.
=> Improve RubyTime predictability
